### ISSUE TITLE
PanoramaView and VideoView for Android

### ISSUE THREAD

**Issue by ozsirma** [tiero/react-native-360#15]
When will PanoramaView and VideoView are available for Android ?

**Comment by chrisk8er** [comment]
Still waiting... 🙄

**Comment by pedrosimao** [comment]
Also waiting for some news concerning Android.

**Comment by fuj1w4r4** [comment]
Any roadmap for android?

**Comment by tiero** [comment]
https://github.com/tiero/react-native-360/issues/24
