### ISSUE TITLE
Mismatch installing from npm registry

### ISSUE THREAD

**Issue by cm-hvg** [tiero/react-native-360#20]
I noticed after installing this plugin that `/components/GVRPanorama.js` is not up to date with what is on master and what was published under `1.0.9`.

When I install using `npm install react-native-360`, the package.json for `react-native-360` is set to version `1.0.9`, but the `GVRPanorama.js` component doesn't include the `prop-types` import changes.

For now, I added the dep using a git URL and it works fine.

**Comment by razvantodea14** [comment]
@cm-hvg I've get the same error  **_react2.PropTypes.string** and when I've tried to use this URL https://github.com/tiero/react-native-360 to install the library I've got an error regarding the **Panorama is not a NativeComponent**. What URL did you used?

**Comment by cidevant** [comment]
+1

**Comment by tiero** [comment]
I think it's better starting requiring from github instead of npm, due lack of time to keep release in sync with the master

I apologize, still looking for maintainers
