### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by SatyaFariz** [tiero/react-native-360#24]
Please add support for android

**Comment by tiero** [comment]
Hi @SatyaFariz, I'm looking for maintainers. https://github.com/tiero/react-native-360/issues/23

If you want to use it on android right away, refer to this  https://github.com/altafan/react-native-gvr-video-android

**Comment by SatyaFariz** [comment]
that lib only supports 360 video. i need support for 360 image view too :(

**Comment by rodymolenaar** [comment]
@SatyaFariz I just published [@lightbasenl/react-native-panorama-view](https://github.com/lightbasenl/react-native-panorama-view). It supports both Android and iOS and loading images from network.

Let me know if it helps you :)
