### ISSUE TITLE
PanoramaView and VideoView doesn't render anything 

### ISSUE THREAD

**Issue by marekpridal** [tiero/react-native-360#4]
I completely follow you Readme but it just doesn't work. Borders are rendered but content isn't. I also tried to install it under react native 0.3.9 instead of 0.4.0 but it didn't change anything. Can you please make readme more specific or fix it to render content as well? Thanks a lot.

**Comment by tiero** [comment]
Hi @marekpridal

let's assume you have the project called **native360** and enter to the **ios** folder (ensure the Podfile was in it)

1)  From terminal pod install && pod update 
2) Open native360.xcworkspace
3) Openin the Finder your project root directory and navigate to **node_modules/react-native-360/ios**
4) Inside there is a folder, drag the **RNGoogleVR** and drop to xCode under your project
5) Clean and Build again

I hope that helps you

In any case checkout the example here https://github.com/tiero/react-native-360/tree/master/example/test

PS: I'm working to drop out CocoaPods but seems very complicated due the Google SDK

**Comment by marekpridal** [comment]
Thanks a lot for help! Unfortunately I am without Mac until Monday, so I'll try it then 🙂

**Comment by marekpridal** [comment]
Hi so finally I got my Mac back. I tried do this tutorial again but it still doesn't work. I am sending screenshot and part of code.

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native';

import { VideoView } from 'react-native-360';

class Play extends Component {

  constructor(props) {
     super(props)
     }

  render() {
    return (
    <View style={styles.view}>
      <Text style={styles.listView}>Playing {this.props.URL}</Text>
      <VideoView
        style={{height:200,width:200}}
        video={{ uri:'http://vr.marekpridal.eu/videoplayback.mp4',
                 type: 'stereo'}}
        displayMode={'embedded'}
        volume={1}
        enableFullscreenButton
        enableCardboardButton
        enableTouchTracking
        hidesTransitionView
        enableInfoButton={false}
    />
    </View>
    );
  }
}

const styles = StyleSheet.create({
  listView: {
      marginTop: 80,
      textAlign: 'center'
  },
  view : {
    backgroundColor: 'white',
    flex: 1
  }
});

module.exports = Play
`

![simulator screen shot 25 1 2017 15 11 33](https://cloud.githubusercontent.com/assets/14936321/22293657/bca6d306-e310-11e6-9b0d-2ee93402f822.png)

**Comment by tiero** [comment]
Hi @marekpridal , can you share your xCode folder structure?

I'm working on experimental hack to use Google VR without CocoaPods that are causing a lot of problem

**Comment by marekpridal** [comment]
![snimek obrazovky 2017-01-25 v 15 39 39](https://cloud.githubusercontent.com/assets/14936321/22294704/8d85545e-e314-11e6-8e33-f3f837cf0a5b.png)

**Comment by tiero** [comment]
Two considerations:

1) Google VR do not works in the simulator [#3](https://github.com/tiero/react-native-360/issues/3)
2) When drag the RNGoogleVR folder to xCode be sure to be as group and copy files

<img width="802" alt="schermata 2017-01-25 alle 15 48 34" src="https://cloud.githubusercontent.com/assets/3596602/22295170/41447e10-e316-11e6-99e5-6adc4660eeba.png">

Let me know

**Comment by marekpridal** [comment]
Great! Now works PanoramaView locally but i cannot load video from server - window stays green. Also when I want to switch to cardboard mode it doesn't work.

**Comment by tiero** [comment]
@marekpridal I think your video is of type mono, set 'mono' in video prop type

The example video is in stereo mode like this below
<img width="779" alt="schermata 2017-01-25 alle 17 02 38" src="https://cloud.githubusercontent.com/assets/3596602/22298286/43904d5c-e320-11e6-9892-c3e6a5a0ac25.png">

**Comment by marekpridal** [comment]
@tiero yeah, it was one thing. But it starts working after I moved panorama view above video view. But still cardboard mode works sometimes more often not and in video doesn't work at all. Anyway thanks a lot for your difficult and great work!
