### ISSUE TITLE
Some question about react-native-360

### ISSUE THREAD

**Issue by ermankuruoglu** [tiero/react-native-360#8]
Hello everyone,

I wonder that, Is this player provides these features in below.

1. I can scroll the video right and left (not in VR mode just only normal video),  but I can not scroll it up and down. How can we achieve this situation?
2. Some videos have high resolution and these videos shown green. I think a green layer show up. I want to see these videos normally.
3. On video running, video scroll not exists on below. Is there any way to show up this scroll for taking video forward and backward.

I will be very happy if I can get some answer my questions.
Best regards.

**Comment by tiero** [comment]
Hi @ermankuruoglu, thank's for reaching out 

1. See this, it's a Google VR bug https://github.com/tiero/react-native-360/issues/3
2. Have you tried to change in the prop `video={{uri:/, type:'stereo'}}` from stereo to mono?
 The green layer is linked to the video format
3. I'm not getting you on this, a 360 video can rotate in hourly or anti-hourly mode.

**Comment by ermankuruoglu** [comment]
Hi @tiero ,

Thanks for your reply,

First and second questions ok. 
I quess there is misunderstanding for my third question. Actually I want to show time slider for video. I am sharing a screenshot. Can we show this in react-native-360 module? Thank you.

![screen shot 2017-03-09 at 15 17 00](https://cloud.githubusercontent.com/assets/21221051/23749918/3238b6be-04d3-11e7-81aa-7f3b112cc9cc.png)

**Comment by tiero** [comment]
To keep the repo organized, Report the third point as an enhancement issue, I will appreciate. Thanks @ermankuruoglu
